# $FreeBSD: projects/armv6/sys/modules/xl/Makefile 226747 2011-10-25 19:47:28Z cognet $

.PATH: ${.CURDIR}/../../dev/xl

KMOD=	if_xl
SRCS=	bus_if.h device_if.h if_xl.c miibus_if.h miidevs.h pci_if.h xlphy.c

.include <bsd.kmod.mk>
