# $FreeBSD: projects/armv6/lib/clang/libllvmx86info/Makefile 232120 2012-02-24 18:39:55Z cognet $

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS=	X86GenInstrInfo \
	X86GenRegisterInfo \
	X86GenSubtargetInfo

.include "../clang.lib.mk"
