# $FreeBSD: projects/armv6/lib/clang/include/Makefile 234858 2012-05-01 04:01:22Z gonzo $

.PATH: ${.CURDIR}/../../../contrib/llvm/tools/clang/lib/Headers

INCSDIR=${INCLUDEDIR}/clang/3.1

INCS=	altivec.h \
	avxintrin.h \
	cpuid.h \
	emmintrin.h \
	immintrin.h \
	mm3dnow.h \
	mm_malloc.h \
	mmintrin.h \
	nmmintrin.h \
	pmmintrin.h \
	smmintrin.h \
	stdalign.h \
	tmmintrin.h \
	unwind.h \
	wmmintrin.h \
	x86intrin.h \
	xmmintrin.h

.include <bsd.init.mk>
.include <bsd.incs.mk>
.include <bsd.obj.mk>
