# $FreeBSD: projects/armv6/lib/clang/libllvmmipsinfo/Makefile 232120 2012-02-24 18:39:55Z cognet $

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS=	MipsGenInstrInfo \
	MipsGenRegisterInfo \
	MipsGenSubtargetInfo

.include "../clang.lib.mk"
