# $FreeBSD: projects/armv6/kerberos5/usr.bin/Makefile 234858 2012-05-01 04:01:22Z gonzo $

SUBDIR=	hxtool kadmin kcc kdestroy kgetcred kf kinit kpasswd krb5-config ksu \
	string2key verify_krb5_conf

.include <bsd.subdir.mk>
