#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/bootparams 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar="bootparamd_enable"
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
