#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/ftp-proxy 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar="ftpproxy_enable"
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
