#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/ftpd 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: ftpd
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpd"
rcvar="ftpd_enable"
command="/usr/libexec/${name}"
pidfile="/var/run/${name}.pid"
start_precmd=ftpd_prestart

ftpd_prestart()
{
	rc_flags="-D ${rc_flags}"
	return 0
}

load_rc_config $name
run_rc_command "$1"
