#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/hostapd 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: hostapd
# REQUIRE: mountcritremote
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="hostapd"
rcvar="hostapd_enable"
command="/usr/sbin/${name}"

conf_file="/etc/${name}.conf"
pidfile="/var/run/${name}.pid"

command_args="-P ${pidfile} -B ${conf_file}"
required_files="${conf_file}"
required_modules="wlan_xauth wlan_wep wlan_tkip wlan_ccmp"
extra_commands="reload"

load_rc_config ${name}
run_rc_command "$1"
