#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/ipxrouted 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: ipxrouted
# REQUIRE: SERVERS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ipxrouted"
rcvar="ipxrouted_enable"
command="/usr/sbin/IPXrouted"
command_args="> /dev/null 2>&1"

load_rc_config $name
run_rc_command "$1"
