#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/keyserv 232120 2012-02-24 18:39:55Z cognet $
#

# Start keyserv if we are running Secure RPC

# PROVIDE: keyserv
# REQUIRE: ypset
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="keyserv"
rcvar="keyserv_enable"
command="/usr/sbin/${name}"
start_precmd="keyserv_prestart"

keyserv_prestart()
{
	force_depend rpcbind || return 1
}

load_rc_config $name
run_rc_command "$1"
