#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/kfd 234858 2012-05-01 04:01:22Z gonzo $
#

# PROVIDE: kfd
# BEFORE: DAEMON

. /etc/rc.subr

name="kfd"
load_rc_config $name
rcvar="kfd_server_enable"
unset start_cmd
command="${kfd_server}"
kfd_flags="-i"
command_args="&"

run_rc_command "$1"
