#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/LOGIN 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON utx

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
