#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/mroute6d 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: mroute6d
# REQUIRE: netif routing
# BEFORE: NETWORKING
# KEYWORD: nojail

. /etc/rc.subr

name="mroute6d"
rcvar="mroute6d_enable"
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
