#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/mrouted 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: mrouted
# REQUIRE: netif routing cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar="mrouted_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
