#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/nfscbd 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
rcvar="nfscbd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
