#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/nfsuserd 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: nfsuserd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfsuserd"
rcvar="nfsuserd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
