#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/rarpd 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON cleanvar
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rarpd"
rcvar="rarpd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ethers"

load_rc_config $name
run_rc_command "$1"
