#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/rpcbind 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar="rpcbind_enable"
command="/usr/sbin/${name}"

stop_postcmd='/bin/rm -f /var/run/rpcbind.*'

load_rc_config $name
run_rc_command "$1"
