#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/rwho 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
rcvar="rwhod_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
