#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/timed 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar="timed_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
