#!/bin/sh
#
# $FreeBSD: projects/armv6/etc/rc.d/utx 232120 2012-02-24 18:39:55Z cognet $
#

# PROVIDE: utx
# REQUIRE: DAEMON cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="utx"
start_cmd="utx boot"
stop_cmd="utx shutdown"

load_rc_config $name
run_rc_command "$1"
