# $FreeBSD: projects/armv6/lib/clang/libclangindex/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	clangindex

SRCDIR=	tools/clang/lib/Index
SRCS=	ASTLocation.cpp \
	Analyzer.cpp \
	DeclReferenceMap.cpp \
	Entity.cpp \
	GlobalSelector.cpp \
	Handlers.cpp \
	IndexProvider.cpp \
	Indexer.cpp \
	Program.cpp \
	SelectorMap.cpp \

TGHDRS=	AttrList \
	Attrs \
	DeclNodes \
	DiagnosticCommonKinds \
	StmtNodes

.include "../clang.lib.mk"
