# $FreeBSD: projects/armv6/lib/clang/libllvmvectorize/Makefile 234353 2012-04-16 21:23:25Z dim $

LIB=	llvmvectorize

SRCDIR=	lib/Transforms/Vectorize
SRCS=	BBVectorize.cpp \
	Vectorize.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
