#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: projects/armv6/usr.bin/ktrace/Makefile 226747 2011-10-25 19:47:28Z cognet $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
