# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: projects/armv6/sbin/routed/rtquery/Makefile 232120 2012-02-24 18:39:55Z cognet $

PROG=	rtquery
MAN=	rtquery.8
LDADD=	-lmd
DPADD=	${LIBMD}
WARNS?=	3
NO_WARRAY_BOUNDS=

.include <bsd.prog.mk>
