# $FreeBSD: projects/armv6/usr.sbin/Makefile.mips 234858 2012-05-01 04:01:22Z gonzo $

# uathload broken for n32 and n64 due to toolchain issues, only build for o32
.if ${MACHINE_ARCH} != "mips" && ${MACHINE_ARCH} != "mipsel"
SUBDIR:=	${SUBDIR:Nuathload}
.endif
