# $FreeBSD: projects/armv6/lib/clang/libllvmmcparser/Makefile 226747 2011-10-25 19:47:28Z cognet $

LIB=	llvmmcparser

SRCDIR=	lib/MC/MCParser
SRCS=	AsmLexer.cpp \
	AsmParser.cpp \
	COFFAsmParser.cpp \
	DarwinAsmParser.cpp \
	ELFAsmParser.cpp \
	MCAsmLexer.cpp \
	MCAsmParser.cpp \
	MCAsmParserExtension.cpp \
	MCTargetAsmParser.cpp

.include "../clang.lib.mk"
