# Makefile for simple caller of syscall
# $FreeBSD: projects/armv6/share/examples/kld/syscall/test/Makefile 203349 2010-02-01 16:13:56Z wkoszek $

PROG=	call
NO_MAN=
WARNS?=	5

.include <bsd.prog.mk>
