# Copyright (c) 2011 David E O'Brien
# $FreeBSD: projects/armv6/lib/libedit/edit/readline/Makefile 234858 2012-05-01 04:01:22Z gonzo $

INCS=	readline.h history.h tilde.h

INCSDIR= ${INCLUDEDIR}/edit/readline

.include <bsd.lib.mk>
