# $FreeBSD: projects/armv6/lib/librtld_db/Makefile 225795 2011-09-27 13:47:23Z cognet $

.include <bsd.own.mk>

LIB=		rtld_db
SHLIB_MAJOR= 	2
MAN=		librtld_db.3

SRCS=		rtld_db.c
INCS=		rtld_db.h

CFLAGS+= -I${.CURDIR}

.include <bsd.lib.mk>
