# $FreeBSD: projects/armv6/lib/clang/libclangfrontendtool/Makefile 212904 2010-09-20 16:43:17Z dim $

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	CC1Options \
	DiagnosticCommonKinds \
	DiagnosticFrontendKinds

.include "../clang.lib.mk"
