# $FreeBSD: projects/armv6/lib/clang/libclangdriver/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	clangdriver

SRCDIR=	tools/clang/lib/Driver
SRCS=	Action.cpp \
	Arg.cpp \
	ArgList.cpp \
	CC1AsOptions.cpp \
	CC1Options.cpp \
	Compilation.cpp \
	Driver.cpp \
	DriverOptions.cpp \
	Job.cpp \
	OptTable.cpp \
	Option.cpp \
	Phases.cpp \
	Tool.cpp \
	ToolChain.cpp \
	ToolChains.cpp \
	Tools.cpp \
	Types.cpp \
	WindowsToolChain.cpp

TGHDRS=	CC1AsOptions \
	CC1Options \
	DiagnosticCommonKinds \
	DiagnosticDriverKinds \
	Options

.include "../clang.lib.mk"
