# $FreeBSD: projects/armv6/lib/clang/libllvmjit/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	llvmjit

SRCDIR=	lib/ExecutionEngine/JIT
SRCS=	JIT.cpp \
	JITDwarfEmitter.cpp \
	JITEmitter.cpp \
	JITMemoryManager.cpp

.include "../clang.lib.mk"
