# $FreeBSD: projects/armv6/sys/modules/geom/geom_part/Makefile 234858 2012-05-01 04:01:22Z gonzo $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_ebr \
	geom_part_gpt \
	geom_part_ldm \
	geom_part_mbr \
	geom_part_pc98 \
	geom_part_vtoc8

.include <bsd.subdir.mk>
