# $FreeBSD: projects/armv6/kerberos5/libexec/Makefile 234858 2012-05-01 04:01:22Z gonzo $

SUBDIR=	digest-service ipropd-master ipropd-slave hprop hpropd kadmind kdc \
	kdigest kfd kimpersonate kpasswdd kcm

.include <bsd.subdir.mk>
