#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: projects/armv6/usr.bin/finger/Makefile 226747 2011-10-25 19:47:28Z cognet $

PROG=	finger
SRCS=	finger.c lprint.c net.c sprint.c util.c
MAN=	finger.1 finger.conf.5

.include <bsd.prog.mk>
