# $FreeBSD: projects/armv6/lib/clang/libllvmarminfo/Makefile 232120 2012-02-24 18:39:55Z cognet $

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS=	ARMGenInstrInfo \
	ARMGenRegisterInfo \
	ARMGenSubtargetInfo

.include "../clang.lib.mk"
