# $FreeBSD: projects/armv6/sys/modules/mmcsd/Makefile 234858 2012-05-01 04:01:22Z gonzo $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmcsd
SRCS=	bus_if.h device_if.h mmcbr_if.h mmcbus_if.h mmcsd.c

.include <bsd.kmod.mk>
