
# $FreeBSD: projects/armv6/kerberos5/lib/Makefile 234858 2012-05-01 04:01:22Z gonzo $

SUBDIR=	libasn1 libgssapi_krb5 libgssapi_ntlm libgssapi_spnego libhdb \
	libheimntlm libhx509 libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers libkdc libwind libheimsqlite libheimbase libheimipcc libheimipcs

.include <bsd.subdir.mk>
