#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: projects/armv6/lib/libc/i386/string/Makefile.inc 232120 2012-02-24 18:39:55Z cognet $

MDSRCS+=bcmp.S bcopy.S bzero.S ffs.S memchr.S memcmp.S memcpy.S memmove.S \
	memset.S strcat.S strchr.S strcmp.S strcpy.S strncmp.S strrchr.S \
	swab.S wcschr.S wcscmp.S wcslen.S wmemchr.S
