# $FreeBSD: projects/armv6/lib/clang/libllvmruntimedyld/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	llvmruntimedyld

SRCDIR=	lib/ExecutionEngine/RuntimeDyld
SRCS=	RuntimeDyld.cpp \
	RuntimeDyldELF.cpp \
	RuntimeDyldMachO.cpp

.include "../clang.lib.mk"
