# $FreeBSD: projects/armv6/lib/clang/libllvmtarget/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Mangler.cpp \
	Target.cpp \
	TargetData.cpp \
	TargetELFWriterInfo.cpp \
	TargetInstrInfo.cpp \
	TargetIntrinsicInfo.cpp \
	TargetJITInfo.cpp \
	TargetLibraryInfo.cpp \
	TargetLoweringObjectFile.cpp \
	TargetMachine.cpp \
	TargetRegisterInfo.cpp \
	TargetSubtargetInfo.cpp

.include "../clang.lib.mk"
