# $FreeBSD: projects/armv6/usr.sbin/cpucontrol/Makefile 232120 2012-02-24 18:39:55Z cognet $

PROG=	cpucontrol
MAN=	cpucontrol.8
SRCS=	cpucontrol.c intel.c amd.c via.c

NO_WCAST_ALIGN=

.include <bsd.prog.mk>
