# $FreeBSD: projects/armv6/tools/tools/wtap/vis_map/Makefile 234858 2012-05-01 04:01:22Z gonzo $

BINDIR?=	/usr/local/bin/
PROG=	vis_map
SRC=	vis_map.c
NO_MAN=	1

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
