# $FreeBSD: projects/armv6/lib/clang/libllvmtablegen/Makefile 234858 2012-05-01 04:01:22Z gonzo $

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	TableGenAction.cpp \
	TableGenBackend.cpp \
	TGLexer.cpp \
	TGParser.cpp
LLVM_REQUIRES_EH=

.include "../clang.lib.mk"
