# $FreeBSD: projects/armv6/lib/clang/libclangedit/Makefile 234353 2012-04-16 21:23:25Z dim $

LIB=	clangedit

SRCDIR=	tools/clang/lib/Edit
SRCS=	Commit.cpp \
	EditedSource.cpp \
	RewriteObjCFoundationAPI.cpp

TGHDRS=	AttrList \
	Attrs \
	DeclNodes \
	StmtNodes \
	DiagnosticCommonKinds

.include "../clang.lib.mk"
